<?php

namespace Tests\Feature;

use Corals\Modules\Utility\Category\Models\Category;
use Corals\Settings\Facades\Modules;
use Corals\User\Models\Role;
use Corals\User\Models\User;
use Illuminate\Foundation\Testing\DatabaseTransactions;
use Illuminate\Support\Facades\Auth;
use Tests\TestCase;

class UtilityCategoryTest extends TestCase
{
    use DatabaseTransactions;

    protected $category = [];

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $user = User::query()->whereHas('roles', function ($query) {
            $query->where('name', 'superuser');
        })->first();
        Auth::loginUsingId($user->id);
    }

    public function test_utility_category_store()
    {
        $modules = [
            'Classified' => 'corals-classified',
            'TroubleTicket' => 'corals-trouble-ticket',
            'Directory' => 'corals-directory',
            'Reservation' => 'corals-reservation',
            'Entity' => 'corals-entity',
        ];
        $categories = ['planet', 'hotel', 'caves', 'streams'];
        $active = false;
        foreach ($modules as $module => $code) {
            if (Modules::isModuleActive($code)) {
                $active = true;
                $category = array_rand($categories);
                $response = $this->post('utilities/categories', [
                    "name" => $category,
                    "slug" => $category,
                    "status" => "active",
                    "module" => $module,
                    "parent_id" => null,
                    "description" => null,
                    "is_featured" => false,
                ]);

                $this->category = Category::query()->first();

                $response->assertRedirect('utilities/categories');
            }
        }

        if (!$active) {
            $category = array_rand($categories);
            $response = $this->post('utilities/categories', [
                "name" => $category,
                "slug" => $category,
                "status" => "active",
                "module" => null,
                "parent_id" => null,
                "description" => null,
                "is_featured" => false,
            ]);
            $this->category = Category::query()->first();

            $response->assertRedirect('utilities/categories');
        }

        $this->assertTrue(true);
    }

    public function test_utility_category_edit()
    {
        if ($this->category) {
            $response = $this->get('utilities/categories/' . $this->category->hashed_id . '/edit');

            $response->assertStatus(200)->assertViewIs('utility-category::categories.create_edit');
        }
        $this->assertTrue(true);
    }

    public function test_utility_category_update()
    {
        if ($this->category) {
            $response = $this->put('utilities/categories/' . $this->category->hashed_id, [
                "name" => $this->category->name,
                "slug" => $this->category->slug,
                "status" => 'inactive',
                "module" => $this->category->module,
                "parent_id" => $this->category->parent_id,
                "description" => $this->category->description,
                "is_featured" => $this->category->is_featured,]);

            $response->assertStatus(200)->assertRedirect('utilities/categories');
        }
        $this->assertTrue(true);
    }

    public function test_utility_category_delete()
    {
        if ($this->category) {
            $response = $this->delete('utilities/categories/' . $this->category->hashed_id);

            $response->assertStatus(200)->assertSeeText('Category has been deleted successfully.');
        }
        $this->assertTrue(true);
    }
}
