<?php

namespace Tests\Feature;

use Corals\User\Models\User;
use Illuminate\Foundation\Testing\DatabaseTransactions;
use Illuminate\Support\Facades\Auth;
use Tests\TestCase;

class UtilityAttributesViewTest extends TestCase
{
    use DatabaseTransactions;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $user = User::query()->whereHas('roles', function ($query) {
            $query->where('name', 'superuser');
        })->first();
        Auth::loginUsingId($user->id);
    }

    /**
     * A basic test example.
     *
     * @return void
     */
    public function test_utility_attribute_view()
    {
        $response = $this->get('utilities/attributes');

        $response->assertStatus(200)->assertViewIs('utility-category::attributes.index');
    }

    public function test_utility_attribute_create()
    {
        $response = $this->get('utilities/attributes/create');

        $response->assertStatus(200)->assertViewIs('utility-category::attributes.create_edit');
    }

    public function test_utility_attribute_bulk_action()
    {
        $response = $this->post('utilities/attributes/bulk-action', [
            'action' => 'delete',]);


        $response->assertSeeText('message');
    }
}
