<?php

namespace Tests\Feature;

use Corals\User\Models\User;
use Illuminate\Foundation\Testing\DatabaseTransactions;
use Illuminate\Support\Facades\Auth;
use Tests\TestCase;

class UtilityCategoryViewTest extends TestCase
{
    use DatabaseTransactions;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $user = User::query()->whereHas('roles', function ($query) {
            $query->where('name', 'superuser');
        })->first();
        Auth::loginUsingId($user->id);
    }

    /**
     * A basic test example.
     *
     * @return void
     */
    public function test_utility_category_view()
    {
        $response = $this->get('utilities/categories');

        $response->assertStatus(200)->assertViewIs('utility-category::categories.index');
    }

    public function test_utility_category_create()
    {
        $response = $this->get('utilities/categories/create');

        $response->assertStatus(200)->assertViewIs('utility-category::categories.create_edit');
    }

    public function test_utility_category_bulk_action()
    {
        $response = $this->post('utilities/categories/bulk-action', [
            'action' => 'active',]);


        $response->assertSeeText('message');
    }

    public function test_utility_category_hierarchy()
    {
        $response = $this->get('utilities/categories/hierarchy');

        $response->assertStatus(200)->assertViewIs('utility-category::categories.hierarchy');
    }
}
